name: MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    name: Run tests
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v6
    - uses: SwiftyLab/setup-swift@latest
     
    - name: Run tests
      run: swift test -v
