# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
     image: swift:6.0-jammy

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Run Benchmark
      run: swift run -c release

